### ISSUE TITLE
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: Operation with name "1453933824116258628" failed with status = GrpcStatusCode{transportCode=INVALID_ARGUMENT} and message = RecognitionAudio not set.

### ISSUE THREAD

**Issue by grale88** [googleapis/java-speech#8]
We are developing a Java application for transcribing audio files. We are using google cloud speech SDK for some time and now we are experiencing the following issue when we start the processing of the files that were previously uploaded to google storage bucket. An additional note is that the code was not changed recently, also the client libraries are used on the same version for some time. We also checked limits for the subscription and everything seems to be in order.

#### Environment details

1. Speech To Text
2. Windows 10/Ubuntu 18.04:
3. Java version: 10.2
4. google-cloud-speech version(s): 1.3.0 and 1.20.0

#### Steps to reproduce

  1. Upload file to google storage
  2. Initiate processing of the file

#### Code example

```
try (SpeechClient speechClient = SpeechClient.create()) {

            RecognitionConfig.Builder configBuilder = RecognitionConfig.newBuilder()
                    .setLanguageCode(request.getLanguageCode())
                    .setEncoding(LINEAR16)
                    .setEnableWordTimeOffsets(true)
                    .setEnableAutomaticPunctuation(true)
                    .setSampleRateHertz(request.getSampleRate());

            RecognitionConfig config = configBuilder.build();

            RecognitionAudio audio = RecognitionAudio.newBuilder()
                    .setUri(googleStorageUri)
                    .build();

            OperationFuture<LongRunningRecognizeResponse, LongRunningRecognizeMetadata> response =
                    speechClient.longRunningRecognizeAsync(config, audio);

            for (int i : List.rangeClosed(1, request.getPollingRetryCount())) {
                if (!response.isDone()) {
                    if (i < request.getPollingRetryCount()) {
                        LOGGER.info("[Google] Request {} not finished. Retry counter {}. Checking again in {} seconds.", request.getRequestId(), i, request.getPollingInterval());
                    } else {
                        LOGGER.info("[Google] Request {} not finished. Retry counter {}.", request.getRequestId(), i);
                    }
                    Thread.sleep(request.getPollingInterval() * 1000);
                } else
                    break;
            }

            if (!response.isDone()) {
                return Either.left(new GenericError("Request timeout on Google AI provider."));
            }

            return Either.right(response.get());

        }
```

#### Stack trace
```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: Operation with name "1453933824116258628" failed with status = GrpcStatusCode{transportCode=INVALID_ARGUMENT} and message = RecognitionAudio not set.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:513) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:82) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62) ~[guava-27.1-jre.jar!/:?]
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:127) ~[gax-1.44.0.jar!/:1.44.0]
	at ai.aiconix.cox.client.GoogleSpeechClient.speechToText(GoogleSpeechClient.java:64) ~[google-plugin-1.10.1-SNAPSHOT.jar!/:1.10.1-SNAPSHOT]
	at ai.aiconix.cox.polling.SpeechToTextActor.lambda$createReceive$1(SpeechToTextActor.java:55) ~[google-plugin-1.10.1-SNAPSHOT.jar!/:1.10.1-SNAPSHOT]
	at io.vavr.control.Either.flatMap(Either.java:373) ~[vavr-0.10.0.jar!/:?]
	at ai.aiconix.cox.polling.SpeechToTextActor.lambda$createReceive$49525aa9$1(SpeechToTextActor.java:55) ~[google-plugin-1.10.1-SNAPSHOT.jar!/:1.10.1-SNAPSHOT]
	at io.vavr.control.Try$WithResources1.lambda$of$97fea75d$1(Try.java:1392) ~[vavr-0.10.0.jar!/:?]
	at io.vavr.control.Try.of(Try.java:75) ~[vavr-0.10.0.jar!/:?]
	at io.vavr.control.Try$WithResources1.of(Try.java:1390) ~[vavr-0.10.0.jar!/:?]
	at ai.aiconix.cox.polling.SpeechToTextActor.lambda$createReceive$5(SpeechToTextActor.java:44) ~[google-plugin-1.10.1-SNAPSHOT.jar!/:1.10.1-SNAPSHOT]
	at io.vavr.control.Either.peek(Either.java:551) ~[vavr-0.10.0.jar!/:?]
	at ai.aiconix.cox.polling.SpeechToTextActor.lambda$createReceive$6(SpeechToTextActor.java:43) ~[google-plugin-1.10.1-SNAPSHOT.jar!/:1.10.1-SNAPSHOT]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123) [scala-library-2.12.4.jar!/:?]
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122) [scala-library-2.12.4.jar!/:?]
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) [scala-library-2.12.4.jar!/:?]
	at akka.actor.Actor.aroundReceive(Actor.scala:517) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at akka.actor.Actor.aroundReceive$(Actor.scala:515) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:147) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at akka.actor.ActorCell.invoke(ActorCell.scala:559) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [akka-actor_2.12-2.5.11.jar!/:2.5.11]
Caused by: com.google.api.gax.rpc.InvalidArgumentException: Operation with name "1453933824116258628" failed with status = GrpcStatusCode{transportCode=INVALID_ARGUMENT} and message = RecognitionAudio not set.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:90) ~[gax-1.44.0.jar!/:1.44.0]
	at com.google.api.gax.grpc.ProtoOperationTransformers$ResponseTransformer.apply(ProtoOperationTransformers.java:57) ~[gax-grpc-1.44.0.jar!/:1.44.0]
	at com.google.api.gax.grpc.ProtoOperationTransformers$ResponseTransformer.apply(ProtoOperationTransformers.java:46) ~[gax-grpc-1.44.0.jar!/:1.44.0]
	at com.google.api.core.ApiFutures$GaxFunctionToGuavaFunction.apply(ApiFutures.java:204) ~[api-common-1.8.1.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:242) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:232) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1138) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:726) ~[guava-27.1-jre.jar!/:?]
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:182) ~[gax-1.44.0.jar!/:1.44.0]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:135) ~[gax-1.44.0.jar!/:1.44.0]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:115) ~[gax-1.44.0.jar!/:1.44.0]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1138) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:726) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:247) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:163) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1138) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:726) ~[guava-27.1-jre.jar!/:?]
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:182) ~[gax-1.44.0.jar!/:1.44.0]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:135) ~[gax-1.44.0.jar!/:1.44.0]
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:115) ~[gax-1.44.0.jar!/:1.44.0]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1138) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:726) ~[guava-27.1-jre.jar!/:?]
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.set(AbstractApiFuture.java:90) ~[api-common-1.8.1.jar!/:?]
	at com.google.api.core.AbstractApiFuture.set(AbstractApiFuture.java:73) ~[api-common-1.8.1.jar!/:?]
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onSuccess(GrpcExceptionCallable.java:88) ~[gax-grpc-1.44.0.jar!/:1.44.0]
	at com.google.api.core.ApiFutures$1.onSuccess(ApiFutures.java:73) ~[api-common-1.8.1.jar!/:?]
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1076) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1138) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958) ~[guava-27.1-jre.jar!/:?]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:726) ~[guava-27.1-jre.jar!/:?]
	at io.grpc.stub.ClientCalls$GrpcFuture.set(ClientCalls.java:502) ~[grpc-stub-1.19.0.jar!/:1.19.0]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:480) ~[grpc-stub-1.19.0.jar!/:1.19.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:699) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.19.0.jar!/:1.19.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) ~[?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:844) ~[?:?]
```

The same issue occurs on newest version of google cloud speech.

**Comment by gordonsan** [comment]
Ditto, just running google-cloud-speech v1.20, code was happily transcribing yesterday.  Tried in the last couple of hours and getting the same error.

Checked https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/speech/cloud-client/src/main/java/com/example/speech/QuickstartSample.java - it works fine as a sync call, but if I mod:
 
	  // Performs speech recognition on the audio file
	  RecognizeResponse response = speechClient.recognize(config, audio);
	  List<SpeechRecognitionResult> results = response.getResultsList();

to an async call:

      System.out.println("Making async request");
      OperationFuture<LongRunningRecognizeResponse, LongRunningRecognizeMetadata> response =
    		  speechClient.longRunningRecognizeAsync(config, audio);
      System.out.println("Async request made " + response.getName());
      while (!response.isDone()) {
        System.out.println("Waiting for response...");
        Thread.sleep(5000);
      }
      System.out.println("getting response");
      LongRunningRecognizeResponse lr_response = response.get();
      List<SpeechRecognitionResult> results = lr_response.getResultsList();

I get..

```
Making async request
Async request made 5189220142130532629
Waiting for response...
getting response
Exception in thread "main" java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: Operation with name "5189220142130532629" failed with status = GrpcStatusCode{transportCode=INVALID_ARGUMENT} and message = RecognitionAudio not set.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:513)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:82)
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62)
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:127)
	at com.example.speech.QuickstartSample.main(QuickstartSample.java:78)
```

**Comment by athakor** [comment]
@grale88 @gordonsan I'm not able to reproduce this issue below are the code snippets and output.

**Code Snippets :**

```
public static void main(String[] args) throws Exception {
    String gcsUri = "gs://bucket-name/hello.wav";
    asyncRecognizeCall(gcsUri);
  }
  public static void asyncRecognizeCall(String gcsUri)  {
    try (SpeechClient speechClient = SpeechClient.create()) {
      RecognitionConfig config =
              RecognitionConfig.newBuilder()
                      .setLanguageCode("en-us")
                      .setEncoding(RecognitionConfig.AudioEncoding.LINEAR16)
                      .setEnableWordTimeOffsets(true)
                      .setAudioChannelCount(2)
                      .setEnableAutomaticPunctuation(true)
                      .setSampleRateHertz(44100)
                      .build();
      RecognitionAudio audio = RecognitionAudio.newBuilder().setUri(gcsUri).build();

      System.out.println("Making async request");
      OperationFuture<LongRunningRecognizeResponse, LongRunningRecognizeMetadata> response = speechClient.longRunningRecognizeAsync(config, audio);
      System.out.println("Async request made " + response.getName());
      while (!response.isDone()) {
        System.out.println("Waiting for response...");
        Thread.sleep(5000);
      }
      System.out.println("getting response");
      LongRunningRecognizeResponse lr_response = response.get();
      System.out.println(lr_response);
      List<SpeechRecognitionResult> results = lr_response.getResultsList();
    }
    catch (Exception e){
      e.printStackTrace();
    }
  }

```
**Output:**

```
Making async request
Async request made 7179279711285457238
Waiting for response...
Waiting for response...
getting response
results {
  alternatives {
    transcript: "Hello."
    confidence: 0.9824453
    words {
      start_time {
      }
      end_time {
        nanos: 300000000
      }
      word: "Hello."
    }
  }
}

```

**Comment by athakor** [comment]
closing this issue due to inactivity feel free to reopen if you face.
